set_property IOSTANDARD LVCMOS33 [get_ports key1]
set_property IOSTANDARD LVCMOS33 [get_ports key2]
set_property IOSTANDARD LVCMOS33 [get_ports led1]
set_property IOSTANDARD LVCMOS33 [get_ports led2]
set_property PACKAGE_PIN R24 [get_ports led1]
set_property PACKAGE_PIN R23 [get_ports led2]
set_property PACKAGE_PIN A26 [get_ports key1]
set_property PACKAGE_PIN A25 [get_ports key2]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets key1_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets key2_IBUF]

set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE Yes [current_design]
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]